const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID:'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_PLAYLIST_ID: 'SET_CUR_PLAYLIST_ID',
    SET_RECENT: 'SET_RECENT',
    SEARCH: 'SEARCH',
    CURRENT_WIDTH: 'CURRENT_WIDTH',

    PLAY: 'PLAY',
    SET_PLAYLIST: 'SET_PLAYLIST',
    PLAYLIST : 'PLAYLIST',
    LOADINGPLAYLIST: 'LOADINGPLAYLIST'
}

export default actionTypes